# Generated by Django 2.0.5 on 2018-07-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gunshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name=['%m/%d/%Y'])),
                ('state', models.CharField(max_length=20)),
                ('city_or_county', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('incident_url_fields_missing', models.BooleanField()),
                ('gun_stolen', models.CharField(max_length=100)),
                ('gun_type', models.CharField(max_length=100)),
                ('incident_charactereristics', models.CharField(max_length=200)),
                ('location_description', models.CharField(max_length=50)),
                ('notes', models.CharField(max_length=200)),
                ('participant_age', models.CharField(max_length=200)),
                ('participant_age_group', models.CharField(max_length=200)),
                ('participant_gender', models.CharField(max_length=200)),
                ('participant_name', models.CharField(max_length=400)),
                ('participant_relationship', models.CharField(max_length=100)),
                ('participant_status', models.CharField(max_length=200)),
            ],
        ),
    ]
