# Generated by Django 2.0.5 on 2018-07-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gunshot',
            name='congressional_district',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gunshot',
            name='incident_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gunshot',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gunshot',
            name='longtitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='gunshot',
            name='n_guns_involved',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gunshot',
            name='n_injured',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gunshot',
            name='n_killed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gunshot',
            name='source_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gunshot',
            name='sources',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gunshot',
            name='state_house_district',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gunshot',
            name='state_senate_district',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gunshot',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name=['%m/%d/%Y']),
        ),
        migrations.AlterField(
            model_name='gunshot',
            name='incident_url_fields_missing',
            field=models.BooleanField(default=False),
        ),
    ]
