# Generated by Django 2.0.5 on 2018-07-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0002_auto_20180712_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunshot',
            name='date',
            field=models.CharField(default='1/1/2010', max_length=20),
        ),
    ]
