# Generated by Django 2.0.5 on 2018-07-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0004_auto_20180715_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunshot',
            name='date',
            field=models.DateField(),
        ),
    ]
