# Generated by Django 2.0.5 on 2018-07-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0005_auto_20180715_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunshot',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
