# Generated by Django 2.0.5 on 2018-07-16 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0006_auto_20180715_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gunshot',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
