# Generated by Django 2.0.5 on 2018-07-16 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0007_auto_20180715_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gunshot',
            old_name='incident_charactereristics',
            new_name='incident_characteristics',
        ),
    ]
