# Generated by Django 2.0.5 on 2018-07-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0010_auto_20180715_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='gunshot',
            name='incident_id',
            field=models.IntegerField(default=0),
        ),
    ]
