# Generated by Django 2.0.5 on 2018-07-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0011_gunshot_incident_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gunshot',
            name='participant_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
