# Generated by Django 2.0.5 on 2018-07-16 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0012_gunshot_participant_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gunshot',
            name='id',
        ),
        migrations.AlterField(
            model_name='gunshot',
            name='incident_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
