# Generated by Django 2.0.5 on 2018-07-17 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0013_auto_20180715_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gunshot',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='gunshot',
            old_name='longitude',
            new_name='lng',
        ),
    ]
