# Generated by Django 2.0.5 on 2018-07-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0014_auto_20180716_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=20)),
                ('state_rank', models.IntegerField(blank=True, null=True)),
                ('total_incidents', models.IntegerField(blank=True, null=True)),
                ('incidents_per_100k', models.FloatField(blank=True, null=True)),
                ('total_killed_n_injured', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
