# Generated by Django 2.0.5 on 2018-07-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0015_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='id',
        ),
        migrations.AlterField(
            model_name='state',
            name='state_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
