# Generated by Django 2.0.5 on 2018-07-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0016_auto_20180722_1852'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('total_incidents', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state_rank',
            new_name='rank',
        ),
    ]
