# Generated by Django 2.0.5 on 2018-08-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_app', '0017_auto_20180724_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=70, primary_key=True, serialize=False),
        ),
    ]
